[Platform API][PSU&COMPONENT]compare applicable data against values from platform.json
Azure/sonic-mgmt pull request #2267
Opened 2020-09-24 23:37 UTC by sujinmkang

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2020-09-24 23:46 UTC, jleveque requested changes

2020-09-24 23:46 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +            logger.warning("Unable to get expected value for '{}' from platform.json file for COMPONENT {}".format(key, component_idx))
s/COMPONENT/component/ (no need for all caps here)

2020-09-24 23:46 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +                      "'{}' value is incorrect. Got '{}', expected '{}' for COMPONENT {}".format(key, value, expected_value, component_idx))
s/COMPONENT/component/ (no need for all caps here)

2020-09-24 23:46 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +                compare_value_with_platform_facts(self, 'name', name, i)
I believe you need to prefix with `self.`, as this is a class method.

2020-09-24 23:46 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +                compare_value_with_platform_facts(self, 'name', name, i)
I believe you need to prefix with `self.`, as this is a class method.

2020-09-24 23:51 UTC, yxieca reviewed
My only concern is that these warnings will be ignored. Had a discussion with Joe offline regarding this on another PR.

I think we could add a specific test to test that platform.json exists and that test can fail and indicating work needed. If the test could further validate required fields and failing on them too, then these warnings are fine.

2020-09-25 01:04 UTC, jleveque commented
@yxieca: I am now of the belief that we should simply consider the platform.json file required, and fail any tests which rely on its data if it's not available. This will result in more consistency across platforms.

Here is a PR for the chassis tests: https://github.com/Azure/sonic-mgmt/pull/2268

2020-09-25 04:08 UTC, jleveque requested changes

2020-09-25 04:08 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +        logger.warning("Unable to get chassis_facts from platform.json, test results will not be comprehensive")
Remove warning message and make the check mandatory. See SFP portion of https://github.com/Azure/sonic-mgmt/pull/2268 for examples.

2020-09-25 04:08 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +            return
Remove warning message and make the check mandatory. See SFP portion of https://github.com/Azure/sonic-mgmt/pull/2268 for examples.

2020-09-25 04:08 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +        logger.warning("Unable to get chassis_facts from platform.json, test results will not be comprehensive")
Remove warning message and make the check mandatory. See SFP portion of https://github.com/Azure/sonic-mgmt/pull/2268 for examples.

2020-09-25 04:08 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +            return
Remove warning message and make the check mandatory. See SFP portion of https://github.com/Azure/sonic-mgmt/pull/2268 for examples.

2020-09-25 06:58 UTC, jleveque requested changes

2020-09-25 06:58 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +        pytest_assert(expected_value is not None,
You should use a nested `self.expect()` here, as this gets called on a number of devices in the list, this way we can gather all the error messages. Please refer ot my SFP changes in https://github.com/Azure/sonic-mgmt/pull/2268, not the chassis changes.

2020-09-25 06:58 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +        pytest_assert(value == expected_value,
You should use a nested `self.expect()` here, as this gets called on a number of devices in the list, this way we can gather all the error messages. Please refer ot my SFP changes in https://github.com/Azure/sonic-mgmt/pull/2268, not the chassis changes.

2020-09-25 06:58 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +        pytest_assert(expected_value is not None,
You should use `self.expect()` here, as this gets called on a number of devices in the list, this way we can gather all the error messages. Please refer ot my SFP changes in https://github.com/Azure/sonic-mgmt/pull/2268, not the chassis changes.

2020-09-25 06:58 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +        pytest_assert(value == expected_value,
You should use a nested `self.expect()` here, as this gets called on a number of devices in the list, this way we can gather all the error messages. Please refer ot my SFP changes in https://github.com/Azure/sonic-mgmt/pull/2268, not the chassis changes.

2020-09-25 17:47 UTC, jleveque requested changes

2020-09-25 17:47 UTC, jleveque commented on tests/platform_tests/api/test_component.py
> +                      "Unable to get expected value for '{}' from platform.json file for component {}".format(key, component_idx))
This is now an `if` statement. It must end with a colon (`:`)

2020-09-25 17:47 UTC, jleveque commented on tests/platform_tests/api/test_psu.py
> +                      "Unable to get expected value for '{}' from platform.json file for PSU {}".format(key, psu_idx))
This is now an `if` statement. It must end with a colon (`:`)

2020-09-25 19:52 UTC, jleveque approved these changes

2020-09-25 21:26 UTC, merged