[doc] How to adapt test cases for SONiC Chassis.
Azure/sonic-mgmt pull request #2511
Opened 2020-11-11 18:40 UTC by sanmalho-git

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
Need a document to outline how the enhancements made to sonic-mgmt can be brought together to adapt existing OC tests to work against a SONiC Chassis.

#### How did you do it?
Added md document

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2020-11-11 18:48 UTC, shubav commented
Could we change the filename to pytest.voq_chassis.md in line with the current convention in that dir?

2020-11-25 03:38 UTC, wangxin requested changes

2020-11-25 03:38 UTC, wangxin commented on tests/docs/pytest.voq_chassis.md
> +The end goal is to be able to run the existing OC tests against a SONiC Chassis with minimal changes to test cases itself.
What is `OC`?

2020-11-25 03:38 UTC, wangxin commented on tests/docs/pytest.voq_chassis.md
> +## 2.2 Parameterizing dut_index and asic_index
The infrastructure has been extended to support below fixtures for parameterizing test cases:
* enum_dut_index
* enum_dut_hostname
* enum_asic_index
* enum_frontend_asic_index
* enum_dut_portname
* enum_dut_portname_oper_up
* enum_dut_portname_admin_up
* enum_dut_portchannel
* enum_dut_portchannel_oper_up
* enum_dut_portchannel_admin_up
* enum_dut_feature
Please update this document accordingly.

2020-11-25 03:38 UTC, wangxin commented on tests/docs/pytest.voq_chassis.md
> +def test_bgp_facts(<b>duthosts, dut_index, asic_index</b>):
Fixtures like `dut_index` and `asic_index` have been updated to `enum_dut_hostname` and `enum_asic_index`. Please update occurrences of the deprecated fixture names accordingly.

2020-12-01 07:27 UTC, merged