[Platform_api test] Rule out non-present Transceivers from SFP Platform API tests
Azure/sonic-mgmt pull request #2550
Opened 2020-11-18 09:46 UTC by keboliu

### Description of PR

Summary:
Fixes # (https://github.com/Azure/sonic-mgmt/issues/2539)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?

In the SFP platform API tests, all test cases assuming that all the SFP are present, but this is not always true.
Some testbed may only have SFP plugged on partial interfaces. 

#### How did you do it?

During the setup phase, check the SFP presence status and rule out the non-present SFP index from the list.

#### How did you verify/test it?

Run platform SFP API tests on the testbed

#### Any platform specific information?

No.

#### Supported testbed topology if it's a new test case?

N/A

### Documentation

2020-11-18 13:48 UTC, liat-grozovik approved these changes

2020-11-18 22:12 UTC, jleveque requested changes
I think we need a way to tell the test whether to expect all transceivers are present or to ignore absent transceivers. If not, there could be an issue where a transceiver is present but the API call is broken and returns non-present and the test would not catch this case.

2020-11-19 08:34 UTC, liat-grozovik commented
Should we use the admin up and assume that for SFPs which are not connected the user should do admin down?

From: Joe LeVeque <notifications@github.com>
Sent: Thursday, November 19, 2020 12:13 AM
To: Azure/sonic-mgmt <sonic-mgmt@noreply.github.com>
Cc: Liat Grozovik <liatg@nvidia.com>; Comment <comment@noreply.github.com>
Subject: Re: [Azure/sonic-mgmt] [Platform_api test] Rule out non-present Transceivers from SFP Platform API tests (#2550)


@jleveque requested changes on this pull request.

I think we need a way to tell the test whether to expect all transceivers are present or to ignore absent transceivers. If not, there could be an issue where a transceiver is present but the API call is broken and returns non-present and the test would not catch this case.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsonic-mgmt%2Fpull%2F2550%23pullrequestreview-533924260&data=04%7C01%7Cliatg%40nvidia.com%7C8a83e6faadd64a7391c208d88c0f2902%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637413344025469125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xz9ReD1vpTECLgD6tudCeHEf8aEdK4VATr53Malue%2Fw%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTABA74CP7G4JQYP6PV2SLSQRBHTANCNFSM4TZXLWZA&data=04%7C01%7Cliatg%40nvidia.com%7C8a83e6faadd64a7391c208d88c0f2902%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637413344025469125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D4ayd5nC%2F7FsG4quWY6Qc9j%2B9ZVHua2u189wVUecG4g%3D&reserved=0>.

2020-11-19 19:58 UTC, jleveque commented
I feel like the test itself should be told whether to expect all transceivers present or to ignore transceivers which are reporting as absent. I don't know of a good method to pass this information to Pytest. Maybe we could check for an environment variable? By default, the test would expect all transceivers present, but if the environment variable is set it will ignore all absent transceivers?

2020-11-20 01:23 UTC, keboliu commented
@liat-grozovik @jleveque although we are able to get the interface "admin up" status from sonic-mgmt, but still it's missing the knowledge about the mapping between the interface and the SFP object index fetched from platform API, it would be too complicated to add this to sonic-mgmt.  I would suggest adding an option to these test cases, by default it will assume all SFP exist, with this option it will only check the present SFPs.

2020-11-20 18:24 UTC, jleveque requested changes

2020-11-20 18:24 UTC, jleveque commented on tests/platform_tests/api/test_sfp.py
> +        self.skip_absent_sfp = request.config.getoption("--skip_absent_sfp")
Suggest using hyphens in lieu of underscores in argument name (e.g., `--skip-absent-sfp`)

2020-11-23 07:37 UTC, liat-grozovik commented
@jleveque and @wangxin any further comments?

2020-11-23 18:30 UTC, jleveque commented
LGTM. @wangxin to review, also.

2020-11-24 12:07 UTC, wangxin approved these changes

2020-11-24 12:07 UTC, wangxin commented
LGTM

2020-11-24 17:25 UTC, jleveque approved these changes

2020-11-24 17:26 UTC, merged