adding test plan for PMON enhancements for chassis
Azure/sonic-mgmt pull request #2695
Opened 2020-12-22 00:22 UTC by rawal01

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach

#### What is the motivation for this PR?

#### How did you do it?
Based on the code changes in the associated PRs:
Configure and show for platform chassis_modules #1145
CHASSIS_STATE_DB on control-card for chassis state #395
PSUd changes to compute power-budget for Modular chassis #104
Introduce APIs for modular chassis support #124
Common power consumption and supply APIs for modular chassis #136
Thermalctld APIs for recording min and max temp #131
Modular Chassis - Midplane monitoring APIs #148
Modular-Chassis: Show midplane status #1267

#### How did you verify/test it?
N/A
#### Any platform specific information?
This is only applicable for distributed VoQ systems

#### Supported testbed topology if it's a new test case?
Only T2 topology as mentioned in PR #2638

The test cases for API are grouped based on test case modules:
 - All tests for api in module_base may be added to test_module.py under api folder
 - All tests for chassis_base may be added to test_chassis.py under api folder
 - All tests for psu_base may be  added to test_psu.py  under api folder
 - All tests for thermal_base may be added to test_thermal under api folder
 - All tests for fan_drawer may be added to test_fan_drawer.py under api folder

### Documentation

2020-12-22 00:40 UTC, shubav commented
@yxieca @jleveque, could you kindly review this?

2020-12-22 21:52 UTC, jleveque requested changes

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +    - [1.2 Configure platform chassis modules](#12-configure-platform-chassis-modules)
Minor: This link does not work.

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +1. Use redis cli dump config db using ``` redis-dump -d 4 -y -k "*CHASSI* ``` after shutdown line card, for example
Use single backticks for inline code, triple backticks for multi-line code blocks. Also suggest using full word `CHASSIS` in the command, e.g., `` `redis-dump -d 4 -y -k "*CHASSIS*` ``

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +2. Use redis cli to dump state Db  ``` redis-dump -d 6 -y -k "*CHASSI* ```
Use single backticks for inline code, triple backticks for multi-line code blocks. Also suggest using full word `CHASSIS` in the command

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +3. Use redis dump  `redis-dump  -d 6 -y -k "*MIDPLANE*"` to get database information
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Use command ``` show chassis-modules status ``` to get status of modular chassis
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Startup line card use Run command ``` sudo config chassis-modules startup <card> ```
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Verify ``` show chassis-modules status ``` report line-card down after shutdown on supervisor
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Verify  ``` show chassis-modules status ``` report line-card up after startup on supervisor
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + *  ``` show chassis-modules status ``` report card status unchanged after shutdown on line card
Use single backticks for inline code

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Use command ` show chassis-modules midplane-status ` to get status of midplane in modular chassis
Remove spaces after opening backtick and before closing backtick.

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +     ```
Suggest aligning with code block above; keep indentation consistent.

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Run command “redis-dump -d 6 -y -k "*TEMP*" on line card
Suggest surrounding commands with single backticks rather than quotes to produce inline code.

2020-12-22 21:52 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> + * Run command “redis-dump -d 6 -y -k "*power*"”
Suggest surrounding commands with single backticks rather than quotes to produce inline code.

2020-12-23 00:09 UTC, jleveque requested changes

2020-12-23 00:09 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +- [APIs for fan_drawer added for modular chassis](#APIs-for-fan_drawer-added-for-modular-chassis)
This link also does not work

2020-12-23 00:09 UTC, jleveque commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +1. Use redis cli dump config db using ` redis-dump -d 4 -y -k "*CHASSIS*" ` after shutdown line card, for example
Remove spaces after opening backtick and before closing backtick. Please do this throughout file for all single backticks.

2020-12-23 02:08 UTC, rawal01 commented on docs/testplan/PMON-Chassis-Enhancements-test-plan.md
> +- [APIs for fan_drawer added for modular chassis](#APIs-for-fan_drawer-added-for-modular-chassis)
@jleveque fixed in latest commit

2020-12-23 02:15 UTC, jleveque approved these changes
Test plan seems sound to me and the document looks good.

@yxieca: Any comments?

2021-01-15 07:29 UTC, merged