[setup-container]: force user name to lower case
Azure/sonic-mgmt pull request #2722
Opened 2020-12-31 13:23 UTC by lguohan

sonic-mgmt image name only allows all lower case. In case the user
name is mixed case, we need to change user name to all lower case.

Signed-off-by: Guohan Lu <lguohan@gmail.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
sonic-mgmt image name only allows all lower case. In case the user
name is mixed case, we need to change user name to all lower case.

#### How did you do it?
change  user name to lower case.

#### How did you verify/test it?
run setup-container when username is mixed case

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2020-12-31 20:15 UTC, theasianpianist requested changes

2020-12-31 20:15 UTC, theasianpianist commented on setup-container.sh
> +LOCAL_IMAGE_NAME=docker-sonic-mgmt-${USER,,}
This method doesn't work for me in non-Bash shells (I think maybe it's not POSIX compliant and Bash specific?). Could we change to something like this?
```suggestion
LOCAL_IMAGE_NAME=docker-sonic-mgmt-`echo "$USER" | tr '[:upper:]' '[:lower:]'`
```

2020-12-31 22:20 UTC, theasianpianist approved these changes

2021-01-01 06:39 UTC, lguohan commented
change not related to the test.

2021-01-01 06:40 UTC, merged