Adjust 'test_snmp_phy_entity' test case to support any number of lanes
Azure/sonic-mgmt pull request #2832
Opened 2021-01-19 06:40 UTC by Junchao-Mellanox

### Description of PR

Summary:
Adjust test case to any type of lanes per cable and not fixed hard coded value of 4 lanes due to recent support of QSFP-DD. 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?

Adjust the test case to support cables which has any number of lanes.

#### How did you do it?

Read lane data from redis and compare it with snmp output.

#### How did you verify/test it?

Manually run the test case

#### Any platform specific information?

N/A

#### Supported testbed topology if it's a new test case?

N/A

### Documentation

2021-01-19 10:59 UTC, keboliu commented
retest vsimage please

2021-01-26 11:09 UTC, liat-grozovik commented
@jleveque  and @qiluo-msft  could you please review this fix/enhancement?

2021-01-26 17:32 UTC, jleveque approved these changes

2021-01-26 22:50 UTC, qiluo-msft commented on tests/snmp/test_snmp_phy_entity.py
> +    'voltage': {'sort_factor': 9000, 'oid_base': SENSOR_TYPE_VOLTAGE, 'extract_line_number': False},
>9000 [](start = 31, length = 4)

How do you choose this number? If it is based on other code, could you provide some code comment to refer that code?

2021-01-26 23:18 UTC, qiluo-msft commented on tests/snmp/test_snmp_phy_entity.py
> +    return eval(content)
>eval [](start = 11, length = 4)

It is dangerous to `eval`. I found a possible solution at [https://stackoverflow.com/a/13165500/2514803](https://stackoverflow.com/a/13165500/2514803)

2021-01-26 23:18 UTC, qiluo-msft requested changes
As comment

2021-01-27 20:53 UTC, qiluo-msft approved these changes

2021-01-27 20:54 UTC, merged