Add test cases test_ro_docker_ps and test_ro_user_docker_ps_all to test sudoers file
Azure/sonic-mgmt pull request #2889
Opened 2021-01-29 20:51 UTC by qiluo-msft

### Description of PR

New test cases to make sure readonly user could run `sudo docker ps [-a]`

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2021-01-29 21:07 UTC, lguohan commented on tests/tacacs/test_ro_user.py
> +    stdout = res['stdout_lines']
can you generalize the check. just check the return value, if it non-zero or non-zero.

I'd like you to cover all command defined in the sudoer file in this pr as well.

2021-01-29 21:07 UTC, lguohan commented on tests/tacacs/test_ro_user.py
> +    assert stdout[0].startwith('CONTAINER ID')
check the return value, do not check the content.

2021-01-29 21:08 UTC, lguohan commented on tests/tacacs/test_ro_user.py
> +    assert stdout[0].startwith('CONTAINER ID')
check return value, do not check the content.

2021-01-30 18:42 UTC, qiluo-msft commented
Retest vsimage please

2021-01-31 08:00 UTC, lguohan commented
can you add the test to kvmtesh t0 suite so that provides check will do the check.

2021-01-31 20:05 UTC, qiluo-msft commented
If I read it correctly, the test cases are already there https://github.com/qiluo-msft/sonic-mgmt/blob/9aabf66662cf165d42bbcbc2f5a888f500da4c73/tests/kvmtest.sh#L142

2021-01-31 22:41 UTC, lguohan commented
I do not think so. can you check the test results to confirm?

2021-01-31 22:42 UTC, lguohan commented on tests/tacacs/test_ro_user.py
> +    stdout = res['stdout_lines']
can you address  this?

2021-01-31 22:43 UTC, lguohan requested changes
please test all ro only cmd defined in the summer file

2021-01-31 22:52 UTC, qiluo-msft commented
I see the test result in https://dev.azure.com/sonicswitch/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/2396/logs/20
```
2021-01-31T08:35:14.3026790Z tacacs/test_ro_user.py::test_ro_user PASSED                              [ 25%]
2021-01-31T08:35:15.6780982Z tacacs/test_ro_user.py::test_ro_user_docker_ps PASSED                    [ 50%]
2021-01-31T08:35:17.0877996Z tacacs/test_ro_user.py::test_ro_user_docker_ps_all PASSED                [ 75%]
2021-01-31T08:35:35.9374924Z tacacs/test_ro_user.py::test_ro_user_ipv6 PASSED                         [100%]
```

2021-01-31 22:55 UTC, lguohan commented
got it

2021-02-01 05:31 UTC, lguohan commented on tests/tacacs/test_ro_user.py
> +def test_ro_user_docker_ps(localhost, duthosts, rand_one_dut_hostname, creds, test_tacacs):
suggest you to combine test_ro_user_docker_ps and test_ro_user_docker_ps_all as a function test_ro_user_sudo_cmds to check all commands that matches the sudoer file.

2021-02-01 08:00 UTC, lguohan approved these changes

2021-02-01 08:00 UTC, lguohan commented
can you please change the pr title and content accordingly?

2021-02-01 16:52 UTC, merged