Pfc tests
Azure/sonic-mgmt pull request #3288
Opened 2021-04-07 08:40 UTC by ANISH-GOTTAPU

### Description of PR
Migration of PFC/PFCWD/ECN tests from `abstract open traffic generator` to `snappi`

Summary:
Test case(new/improvement)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
The motivation for this PR is to migrate the tests that are written with `abstract open traffic generator` to `snappi`

#### How did you do it?
Replaced the code where abstract is used to snappi

#### How did you verify/test it?
verified all the tests in sonic-mgmt using pytest with DUT and IXIA connections 
snappi version used for the development of tests `snappi[ixnetwork]==0.3.13`

2021-04-07 08:43 UTC, ANISH-GOTTAPU commented
adding snappi[ixnetwork] installation in Dockerfile.j2 will be addressed in this https://github.com/Azure/sonic-buildimage/pull/7204, The version will be upgraded to snappi[ixnetwork]==0.3.13

2021-04-07 15:26 UTC, neethajohn requested changes

2021-04-07 15:26 UTC, neethajohn commented on tests/common/ixia/ixia_fixtures.py
> +def snappi_api(ixia_api_serv_ip,
please move the snappi api's to a diff file

2021-04-07 15:26 UTC, neethajohn commented on tests/common/ixia/ixia_fixtures.py
> +    config = snappi_api.config()
let's leave this method intact and have the snappi setup done in a separate method

2021-04-07 15:27 UTC, neethajohn commented
Please split this PR into smaller ones - a separate one for pfc, pfcwd and ecn which will make it easier to review

2021-04-08 13:46 UTC, ANISH-GOTTAPU commented
closing this PR as per review comments, opened https://github.com/Azure/sonic-mgmt/pull/3298 for PFC to address review comments

2021-04-08 13:46 UTC, closed without merging