[rdma] Support portchannel interfaces in the topology
Azure/sonic-mgmt pull request #3300
Opened 2021-04-09 08:47 UTC by baiwei0427

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2021-04-09 21:34 UTC, yxieca commented
@baiwei0427 looks like your change was affecting the kvm test and caused failures.

2021-04-09 21:40 UTC, baiwei0427 commented
> @baiwei0427 looks like your change was affecting the kvm test and caused failures.

What should I do to fix it?

2021-04-14 17:18 UTC, neethajohn requested changes

2021-04-14 17:18 UTC, neethajohn commented on tests/common/ixia/common_helpers.py
> +def get_intf_ipv4_addr(host_ans):
not needed. This is also in mg_facts as stated above

Sample dump:
"minigraph_portchannel_interfaces": [{"addr": "10.0.0.56", "attachto": "PortChannel0001", "mask": "255.255.255.254", "peer_addr": "10.0.0.57", "prefixlen": 31, "subnet": "10.0.0.56/31"}
"minigraph_vlan_interfaces": [{"addr": "192.168.0.1", "attachto": "Vlan1000", "mask": "255.255.248.0", "prefixlen": 21, "subnet": "192.168.0.0/21"}],

2021-04-14 17:18 UTC, neethajohn commented on tests/common/ixia/port.py
> +            duthost.shell('sudo config interface shutdown {}'.format(dut_port))
We don't need to do this anymore since we are only using single portchannel member

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/conftest.py
> +            intfs = pc_member[pc]
intfs should be a list here

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/conftest.py
> +            if len(intfs) > 1:
This should be outside the for loop in L90

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/conftest.py
> +@pytest.fixture(autouse=True, scope="module")
remove the autouse=True since we don't need this anymore

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/conftest.py
> +@pytest.fixture(autouse=True, scope="module")
remove autouse=True

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/pfc/test_pfc_pause_lossless.py
> +#@pytest.mark.skip(reason="no way of currently testing this")
remove

2021-04-14 17:18 UTC, neethajohn commented on tests/ixia/pfc/test_pfc_pause_lossless.py
> +#@pytest.mark.skip(reason="no way of currently testing this")
remove

2021-04-15 15:53 UTC, neethajohn approved these changes

2021-04-15 15:54 UTC, merged