[Mellanox] update sensor test case for MSN4600 A0 and A1 system
Azure/sonic-mgmt pull request #3547
Opened 2021-05-27 11:47 UTC by keboliu

### Description of PR

Summary:

Update sku-sensors-data.yml  and test_sensors.py to support Mellanox MSN4600 A0 and A1 system.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
To have sensor test support Mellanox MSN4600 A0 and A1 system. 

#### How did you do it?
Add MSN4600 A0 and A1 sensor data to sku-sensors-data.yml 
Update test_sensors.py to differentiate A0 and A1 system.

#### How did you verify/test it?

Run sensor test against Mellanox 4600 A0 and A1 system.

#### Any platform specific information?
Change only take effect on the Mellanox platform.

#### Supported testbed topology if it's a new test case?

### Documentation

2021-05-27 16:54 UTC, jleveque approved these changes

2021-05-27 16:55 UTC, jleveque requested changes

2021-05-27 16:55 UTC, jleveque commented on tests/platform_tests/test_sensors.py
> +    if platform == 'x86_64-mlnx_msn4700-r0' or platform == 'x86_64-mlnx_msn4600-r0':
Suggest changing to:

```
if platform in ['x86_64-mlnx_msn4700-r0', 'x86_64-mlnx_msn4600-r0']:
```

2021-05-28 08:08 UTC, keboliu commented
@jleveque  comments addressed, please help to check agian.

2021-05-28 16:36 UTC, jleveque approved these changes

2021-05-30 07:05 UTC, liat-grozovik approved these changes

2021-05-30 08:23 UTC, merged