Pfc tests migration from abstract to snappi
Azure/sonic-mgmt pull request #3641
Opened 2021-06-08 14:12 UTC by ANISH-GOTTAPU

### Description of PR
Migration of PFC tests from `abstract open traffic generator` to `snappi`

Summary:
Test case(new/improvement)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
The motivation for this PR is to migrate the tests that are written with `abstract open traffic generator` to `snappi`

#### How did you do it?
Replaced the code where abstract is used to snappi

#### How did you verify/test it?
verified all the tests in sonic-mgmt using pytest with DUT and IXIA connections 
snappi version used for the development of tests `snappi[ixnetwork]==0.4.0`

2021-07-08 07:12 UTC, baiwei0427 requested changes

2021-07-08 07:12 UTC, baiwei0427 commented on tests/common/fixtures/snappi_fixtures.py
> +"""
This file is also created in https://github.com/Azure/sonic-mgmt/pull/3653/

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/conftest.py
> +from tests.common.ixia.common_helpers import enable_packet_aging, start_pfcwd
Use tests.common.snappi.common_helpers instead.

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_global_pause_with_snappi.py
> +from tests.common.ixia.qos_fixtures import prio_dscp_map, all_prio_list, lossless_prio_list,\
ixia -> snappi

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_global_pause_with_snappi.py
> +pytestmark = [pytest.mark.topology('tgen')]
@pytest.mark.topology("snappi")

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_pfc_pause_lossless_with_snappi.py
> +from tests.common.ixia.qos_fixtures import prio_dscp_map, all_prio_list, lossless_prio_list,\
ixia -> snappi

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_pfc_pause_lossless_with_snappi.py
> +pytestmark = [pytest.mark.topology('tgen')]
tgen -> snappi

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_pfc_pause_lossy_with_snappi.py
> +from tests.common.ixia.qos_fixtures import prio_dscp_map, all_prio_list, lossless_prio_list,\
ixia -> snappi

2021-07-08 07:12 UTC, baiwei0427 commented on tests/snappi/pfc/test_pfc_pause_lossy_with_snappi.py
> +pytestmark = [pytest.mark.topology('tgen')]
tgen -> snappi

2021-07-08 07:26 UTC, ANISH-GOTTAPU commented
@baiwei0427 : This PR was raised before test_snappi, once test_snappi is merged, I will pull the master and update this PR accordingly

2021-07-08 07:27 UTC, baiwei0427 commented
> @baiwei0427 : This PR was raised before test_snappi, once test_snappi is merged, I will pull the master and update this PR accordingly

Thanks! Please change all 'ixia' and 'tgen' to 'snappi'

2021-07-14 12:57 UTC, ANISH-GOTTAPU commented
closing this as it is addressed in #3794

2021-07-14 12:57 UTC, closed without merging