Modifying tests to adapt to new config reload system checks
Azure/sonic-mgmt pull request #3657
Opened 2021-06-10 23:28 UTC by dgsudharsan

### Description of PR

Modify sonic-mgmt test cases to handle new config reload behavior. Config reload will perform system checks before proceeding. If the listed system checks fail config reload will not execute.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### Approach
#### What is the motivation for this PR?
To enhance the test cases as per new config reload behavior.

#### How did you do it?
Added system check in tests before executing config reload command so that it would not fail. Additionally add new test case to validate config reload command behavior.

#### How did you verify/test it?
Run config reload platform tests.

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2021-06-19 16:24 UTC, dgsudharsan commented
@yxieca @jleveque Can you please review the changes? This can be merged ahead of config reload fixes as this is backward compatible.

2021-06-20 16:41 UTC, liat-grozovik approved these changes

2021-06-21 21:40 UTC, jleveque requested changes

2021-06-21 21:40 UTC, jleveque commented on tests/common/config_reload.py
> +        wait_until(300,20,config_system_checks_passed, duthost)
Add space after commas

2021-06-21 22:50 UTC, jleveque approved these changes
Looks good to me. I would like someone from @Azure/sonic-fundamentals to review, as well.

2021-06-22 20:41 UTC, yxieca approved these changes

2021-06-22 20:52 UTC, merged