Vanram 4byte asn testlatest
Azure/sonic-mgmt pull request #4632
Opened 2021-11-05 02:14 UTC by vaniramdurg

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### Approach
#### What is the motivation for this PR?
test_bgp_speaker.py is the motivation for this PR
#### How did you do it?
Added blocks that can change DUT and/or bgp speaker configuration to configure 4byte ASN.
#### How did you verify/test it?
I ran the ./run_test command and tested exabgp session establishment, route announce, and traffic send and receive.
#### Any platform specific information?
Currently tested with t0 and PTF.
#### Supported testbed topology if it's a new test case?
Sonic t0 with ceos neighbors.
### Documentation

2021-11-12 03:13 UTC, lguohan commented on tests/bgp/test_bgp_speaker_2b4b.py
> +The script is similar to test_bgp_speaker.py, except that bgp speaker ASN modification.
please reuse the test_bgp_speaker.py test, do not create a new test. we need to reuse our code. having duplicated code increase the cost of maintainance

2021-11-12 03:13 UTC, lguohan requested changes
please reuse the test_bgp_speaker.py test, do not create a new test. we need to reuse our code. having duplicated code increase the cost of maintainance

2021-11-12 03:14 UTC, lguohan commented on docs/testplan/BGP-Speaker-2byte-to-4byte-ASN.md
> +Configure IXIA/Spirent with a 4-byte ASN and peer with DUT.
why ixia here? are we using ixia here? if not, please remove from the description.

2021-11-24 19:02 UTC, closed without merging

2021-11-24 19:02 UTC, vaniramdurg commented
Created another one based on review comments. Merged these changes inside test_bgp_speaker.py