[everflow] Fixed everflow_per_interface import error
Azure/sonic-mgmt pull request #4655
Opened 2021-11-09 12:24 UTC by SavchukRomanLv

Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>

### Description of PR

Summary:
Fixes type error when run everflow_per_interface TC
`def apply_mirror_session(rand_selected_dut):`
       `mirror_session_info = BaseEverflowTest.mirror_session_info(EVERFLOW_SESSION_NAME,` 
       `rand_selected_dut.facts["asic_type"])`
       `TypeError: mirror_session_info() takes exactly 3 arguments (2 given)`

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### Approach
#### What is the motivation for this PR?
Run everflow_per_interface
#### How did you do it?
Added missing arg
#### How did you verify/test it?
No type error appears, config applied to DUT
#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2021-11-10 00:42 UTC, bingwang-ms commented
I didn't see the error you ran into. Could you double-confirm?
For reference

https://github.com/Azure/sonic-mgmt/blob/aa334707d429ff164e799d37c4125710e366894d/tests/everflow/everflow_test_utilities.py#L644-671

2021-11-10 01:23 UTC, wangxin approved these changes

2021-11-10 01:25 UTC, wangxin requested changes
Approved too early before noticing the comments from @bingwang-ms

2021-11-15 13:28 UTC, SavchukRomanLv commented
@wangxin @bingwang-ms closing this

2021-11-15 13:28 UTC, closed without merging