[test gap] add memory exhaustion test
Azure/sonic-mgmt pull request #5260
Opened 2022-03-01 11:17 UTC by lizhijianrd

### Description of PR

Validate kernel will panic and reboot the DUT when kernel runs out of memory and hit oom event.

Summary:
Fixes #3619 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### Approach
#### What is the motivation for this PR?

Validate kernel will panic and reboot the DUT when kernel runs out of memory and hit oom event.

#### How did you do it?

Use `tail /dev/zero` to run out of memory completely and check the DUT reboot as expected.

#### How did you verify/test it?

Run tests on vSONiC and physical DUTs.

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-03-01 11:57 UTC, Blueve commented on tests/platform_tests/test_memory_exhaustion.py
> +def test_memory_exhaustion(duthosts, enum_frontend_dut_hostname, localhost):
@liuh-80 Is this test expected after your OOM protection merged?

2022-03-03 06:13 UTC, Blueve requested changes

2022-03-03 11:18 UTC, lizhijianrd commented on tests/platform_tests/test_memory_exhaustion.py
> +        raise Exception('DUT {} did not shutdown'.format(hostname))
@Blueve Thank you! I updated my code in commit https://github.com/Azure/sonic-mgmt/pull/5260/commits/6c0a36a4c815b5e1f3d1d2364bb29ee69f54dadf. I hope this problem is fixed.

2022-03-03 11:19 UTC, lizhijianrd commented on tests/platform_tests/test_memory_exhaustion.py
> +        raise Exception('DUT {} did not startup'.format(hostname))
@Blueve Thank you! I updated my code in commit https://github.com/Azure/sonic-mgmt/pull/5260/commits/6c0a36a4c815b5e1f3d1d2364bb29ee69f54dadf. I hope this problem is fixed.

2022-03-04 04:10 UTC, Blueve commented on tests/platform_tests/test_memory_exhaustion.py
> +def test_memory_exhaustion(duthosts, enum_frontend_dut_hostname, localhost):
Let's sync this later. Before the feature merged, the test should be valid

2022-03-04 07:35 UTC, Blueve commented on tests/platform_tests/test_memory_exhaustion.py
> +def test_memory_exhaustion(duthosts, enum_frontend_dut_hostname, localhost):
Confirmed with Hua, this is still a expected test case.

2022-03-09 08:56 UTC, Blueve commented on tests/platform_tests/test_memory_exhaustion.py
> +import logging
Let's move this test to other place in a new PR if need.

2022-03-09 08:57 UTC, Blueve approved these changes

2022-03-09 09:08 UTC, merged

2022-03-11 03:02 UTC, wangxin commented
This PR should not go to 202012 branch. I have reverted it in 202012 branch.