Skipping test for absent modules
Azure/sonic-mgmt pull request #5680
Opened 2022-05-18 19:54 UTC by vperumal

### Description of PR
Currently the tests are trying to access modules which are not present and failing for them. Even though there is a skip_mod_list, there is no code present to use it. Added the support for it in all the relevant cases.

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### Approach
#### What is the motivation for this PR?
Currently the tests are trying to access modules which are not present and failing for them. Even though there is a skip_mod_list, there is no code present to use it. Added the support for it in all the relevant cases.

#### How did you do it?

#### How did you verify/test it?
Verified on cisco-8000 platform for T2 profile

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-05-18 19:55 UTC, vperumal commented
FYI @abdosi @SuvarnaMeenakshi

2022-06-01 21:51 UTC, gechiang requested changes

2022-06-01 21:51 UTC, gechiang commented on tests/platform_tests/api/test_module.py
> +            if self.skip_absent_module(i,platform_api_conn):
I think you should move this to immediately after you enter the for loop and only if it passed then execute the original code to get name and others...

2022-06-01 21:51 UTC, gechiang commented on tests/platform_tests/api/test_module.py
> +            name = module.get_name(platform_api_conn, i)
why do you need this name?

2022-06-01 21:51 UTC, gechiang commented on tests/platform_tests/api/test_module.py
> +            name = module.get_name(platform_api_conn, i)
Same here. What is the purpose of this "name" here? copy and paste issue?

2022-06-01 21:51 UTC, gechiang commented on tests/platform_tests/api/test_module.py
> +            name = module.get_name(platform_api_conn, i)
this line is not needed right?

2022-06-02 03:15 UTC, vperumal commented
Hi @gechiang, made changes as per your review comments

2022-06-02 15:49 UTC, gechiang approved these changes

2022-06-08 05:31 UTC, merged